export const COMMON_GET_REFERRAL_FILES = 'COMMON_GET_REFERRAL_FILES';
export const COMMON_GET_REFERRAL_FILES_BEGIN = 'COMMON_GET_REFERRAL_FILES_BEGIN';
export const COMMON_GET_REFERRAL_FILES_SUCCESS = 'COMMON_GET_REFERRAL_FILES_SUCCESS';
export const COMMON_GET_REFERRAL_FILES_FAILURE = 'COMMON_GET_REFERRAL_FILES_FAILURE';
export const COMMON_GET_REFERRAL_FILES_DISMISS_ERROR = 'COMMON_GET_REFERRAL_FILES_DISMISS_ERROR';
